"""Reusable core abstractions for config-first ML autoresearch."""

from autoresearch_core.contracts import (
    AnalyticsSnapshot,
    CandidateProposal,
    LoopSnapshot,
    ProjectAdapter,
    ProjectConfigHandle,
    RunResult,
    RunSpec,
    SelectionContext,
    SelectionDecision,
    SupportsRunResult,
)
from autoresearch_core.engine import (
    LoopControlResolution,
    LoopProgressState,
    ProviderSelectionResult,
    build_run_result,
    candidate_payloads,
    initialize_progress_state,
    recent_policy_results,
    resolve_loop_control,
    resolve_provider_selection,
    result_snapshot,
    run_loop_schedule,
)
from autoresearch_core.training import (
    LoopAwareTrainingControl,
    NoOpTrainingControl,
    NoOpTrainingHooks,
    TrainingControl,
    TrainingHooks,
    WriterBackedTrainingHooks,
)

__all__ = [
    "AnalyticsSnapshot",
    "CandidateProposal",
    "candidate_payloads",
    "LoopControlResolution",
    "LoopAwareTrainingControl",
    "LoopProgressState",
    "LoopSnapshot",
    "NoOpTrainingControl",
    "NoOpTrainingHooks",
    "ProjectAdapter",
    "ProjectConfigHandle",
    "ProviderSelectionResult",
    "build_run_result",
    "RunResult",
    "RunSpec",
    "SelectionContext",
    "SelectionDecision",
    "SupportsRunResult",
    "TrainingControl",
    "TrainingHooks",
    "WriterBackedTrainingHooks",
    "initialize_progress_state",
    "recent_policy_results",
    "result_snapshot",
    "run_loop_schedule",
    "resolve_loop_control",
    "resolve_provider_selection",
]
